import '../css/header.css';
export const metadata = {
  title: 'a5hi5hx',
  description: 'Generated by a5hi5hx',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<>
  <html lang="en">
      <body>
      <header>
            <nav>
                <input type="checkbox" id="nav-toggle" />
                <div className="logo">Hello<strong>CODE</strong></div>
                <ul className="links">
                    <li><a href="#home">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#work">Work</a></li>
                    <li><a href="#projects">Projects</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
                <label htmlFor="nav-toggle" className="icon-burger">
                    <div className="line"></div>
                    <div className="line"></div>
                    <div className="line"></div>
                </label>
            </nav>
        </header>
        {children}
        <footer style={{backgroundColor: "lightblue", padding: "5rem"}}>
        <p>&copy; 2024 My Website. All rights reserved.</p>       
         </footer>
        </body>
    </html> 
    </>
  );
}
