export const metadata = {
  title: 'Next.js',
  description: 'Generated by Ashish',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "cyan", padding: "5rem"}}>
This is header..................................................
        </header>
        {children}
        <footer style={{backgroundColor: "lightblue", padding: "5rem"}}>
This is footer..................................................
        </footer>
        </body>
    </html>
  )
}
